export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN/REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN/SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN/FAILED';
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER/REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER/SUCCESS';
export const AUTH_REGISTER_FAILED = 'AUTH_REGISTER/FAILED';
