export const GET_FRIEND_RELATION_REQUEST = 'GET_FRIEND_RELATION/REQUEST';
export const GET_FRIEND_RELATION_SUCCESS = 'GET_FRIEND_RELATION/SUCCESS';
export const GET_FRIEND_RELATION_FAILED  = 'GET_FRIEND_RELATION/FAILED';

export const MAKE_FRIENDS_REQUEST  = 'MAKE_FRIENDS/FAILED';
export const MAKE_FRIENDS_SUCCESS  = 'MAKE_FRIENDS/FAILED';
export const MAKE_FRIENDS_FAILED  = 'MAKE_FRIENDS/FAILED';
