export const GET_FRIEND_RELATION_REQUEST = 'GET_FRIEND_RELATION/REQUEST';
export const GET_FRIEND_RELATION_SUCCESS = 'GET_FRIEND_RELATION/SUCCESS';
export const GET_FRIEND_RELATION_FAILED  = 'GET_FRIEND_RELATION/FAILED';

export const MAKE_FRIENDS_REQUEST  = 'MAKE_FRIENDS/FAILED';
export const MAKE_FRIENDS_SUCCESS  = 'MAKE_FRIENDS/FAILED';
export const MAKE_FRIENDS_FAILED  = 'MAKE_FRIENDS/FAILED';

export const GET_FRIENDS_REQUEST = 'GET_FRIENDS/REQUEST';
export const GET_IN_REQUESTS_REQUEST = 'GET_IN_REQUESTS/REQUEST';
export const GET_OUT_REQUESTS_REQUEST = 'GET_OUT_REQUESTS/REQUEST';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS/SUCCESS';
export const GET_FRIENDS_FAILED = 'GET_FRIENDS/FAILED';

export const CHANGE_SELECTED_FRIENDS_TAB = 'CHANGE_SELECTED_FRIENDS_TAB/CHANGE';
