export const POST_GET_REQUEST = 'POST_GET/REQUEST';
export const POST_GET_SUCCESS = 'POST_GET/SUCCESS';
export const POST_GET_FAILED = 'POST_GET/FAILED';

export const POST_CREATE_REQUEST = 'POST_CREATE/REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE/SUCCESS';
export const POST_CREATE_FAILED = 'POST_CREATE/FAILED';

export const POST_PICTURE_CHOOSE = 'POST_PICTURE/CHOOSE';
