export const POST_GET_REQUEST = 'POST_GET/REQUEST';
export const POST_GET_SUCCESS = 'POST_GET/SUCCESS';
export const POST_GET_FAILED = 'POST_GET/FAILED';

export const POST_CREATE_REQUEST = 'POST_CREATE/REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE/SUCCESS';
export const POST_CREATE_FAILED = 'POST_CREATE/FAILED';

export const POST_PICTURE_CHOOSE = 'POST_PICTURE/CHOOSE';

export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS/REQUEST';
export const GET_USER_MORE_POSTS_REQUEST = 'GET_USER_MORE_POSTS/REQUEST';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS/SUCCESS';
export const GET_USER_POSTS_FAILED = 'GET_USER_POSTS/FAILED';

export const GET_FEED_POSTS_REQUEST = 'GET_FEED_POSTS/REQUEST';
export const GET_FEED_MORE_POSTS_REQUEST = 'GET_FEED_MORE_POSTS/REQUEST';
export const GET_FEED_POSTS_SUCCESS = 'GET_FEED_POSTS/SUCCESS';
export const GET_FEED_POSTS_FAILED = 'GET_FEED_POSTS/FAILED';
