export const USER_GET_REQUEST = 'USER_GET/REQUEST';
export const USER_GET_SUCCESS = 'USER_GET/SUCCESS';
export const USER_GET_FAILED = 'USER_GET/FAILED';

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER/REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER/SUCCESS';
export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER/FAILED';
